<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>net.sf.lightair</groupId>
	<artifactId>light-air</artifactId>
	<version>3.3.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>Light Air</name>
	<description>Integration functional testing of web applications for developers.</description>
	<url>http://lightair.sourceforge.net</url>
	<inceptionYear>2011</inceptionYear>
	<organization>
		<name>Lastware, sro.</name>
		<url>http://www.lastware.cz</url>
	</organization>
	<developers>
		<developer>
			<id>imaixner</id>
			<name>Ivo Maixner</name>
			<email>ivo (.) maixner (at) gmail (.) com</email>
			<timezone>+1</timezone>
		</developer>
		<developer>
			<id>effy</id>
			<name>Petr Effenberger</name>
			<email>petr (at) effy (.) cz</email>
			<timezone>+1</timezone>
		</developer>
		<developer>
			<id>katox</id>
			<name>Kamil Toman</name>
			<email>kamil (.) toman (at) leafclick (.) com</email>
			<timezone>+1</timezone>
		</developer>
		<developer>
			<id>hadasj</id>
			<name>Jan Hadaš</name>
			<timezone>+1</timezone>
		</developer>
		<developer>
			<id>premeks</id>
			<name>Přemek Špička</name>
			<timezone>+1</timezone>
		</developer>
	</developers>
	<licenses>
		<license>
			<name>Apache License, Version 2.0</name>
			<url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
	</licenses>
	<issueManagement>
		<system>GitHub</system>
		<url>https://github.com/ivos/lightair/issues</url>
	</issueManagement>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<junitVersion>4.13.2</junitVersion>
		<testngVersion>6.14.3</testngVersion>

		<h2Version>2.2.220</h2Version>
		<hsqlVersion>2.7.4</hsqlVersion>
	</properties>
	<scm>
		<connection>scm:git:git@github.com:ivos/lightair.git</connection>
		<developerConnection>scm:git:git@github.com:ivos/lightair.git</developerConnection>
		<url>https://github.com/ivos/lightair</url>
		<tag>HEAD</tag>
	</scm>
	<distributionManagement>
		<snapshotRepository>
			<id>sonatype-nexus-snapshots</id>
			<name>Sonatype Nexus Snapshots</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<uniqueVersion>false</uniqueVersion>
		</snapshotRepository>
		<repository>
			<id>sonatype-nexus-staging</id>
			<name>Nexus Release Repository</name>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
		</repository>
		<site>
			<id>lightair.sf.net</id>
			<url>scp://shell.sourceforge.net/home/project-web/lightair/htdocs/</url>
		</site>
	</distributionManagement>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.zonky.test.postgres</groupId>
				<artifactId>embedded-postgres-binaries-bom</artifactId>
				<version>16.10.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>

		<!-- JUnit -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<!-- ! version extracted to ${junitVersion} for project-setup.apt.vm -->
			<version>${junitVersion}</version>
			<exclusions>
				<exclusion>
					<groupId>junit</groupId>
					<artifactId>junit-dep</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.hamcrest</groupId>
					<artifactId>hamcrest-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- TestNG -->
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${testngVersion}</version>
			<optional>true</optional>
		</dependency>

		<!--Spring test runner-->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-test</artifactId>
			<version>5.3.39</version>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.0.1</version>
			<optional>true</optional>
		</dependency>

		<!-- Apache commons -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.18.0</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.16.1</version>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.18.0</version>
		</dependency>

		<!-- Joda time -->
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<version>2.2</version>
		</dependency>

		<!-- Logging, SLF4J -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.5</version>
		</dependency>
		<dependency>
			<!-- spring-jdbc in test logs via jcl, route to slf4j: -->
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
			<version>1.7.5</version>
			<scope>runtime</scope>
		</dependency>

		<!-- test (compile): -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
			<version>5.3.39</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.sf.seaf</groupId>
			<artifactId>seaf-test-commons</artifactId>
			<version>1.6</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jmock</groupId>
			<artifactId>jmock</artifactId>
			<version>2.5.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-core</artifactId>
			<version>1.1</version>
			<scope>test</scope>
		</dependency>

		<!-- test (runtime): -->
		<dependency>
			<groupId>org.jmock</groupId>
			<artifactId>jmock-legacy</artifactId>
			<version>2.5.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>${h2Version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hsqldb</groupId>
			<artifactId>hsqldb</artifactId>
			<version>${hsqlVersion}</version>
			<classifier>jdk8</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>42.7.7</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.zonky.test</groupId>
			<artifactId>embedded-postgres</artifactId>
			<version>2.1.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.zonky.test.postgres</groupId>
			<artifactId>embedded-postgres-binaries-darwin-amd64</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.zonky.test.postgres</groupId>
			<artifactId>embedded-postgres-binaries-darwin-arm64v8</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- Oracle jdbc driver must be copied into jre/lib/ext directory in the JDK. -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>5.3.39</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.5.13</version>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>
		<testResources>
			<testResource>
				<directory>src/test/resources</directory>
			</testResource>
			<testResource>
				<directory>src/test/java</directory>
				<includes>
					<include>**</include>
				</includes>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</testResource>
		</testResources>
		<pluginManagement>
			<plugins>
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.5.1</version>
					<configuration>
						<source>${maven.compiler.source}</source>
						<target>${maven.compiler.target}</target>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-site-plugin</artifactId>
					<version>3.21.0</version>
					<configuration>
						<chmod>false</chmod>
					</configuration>
					<dependencies>
						<!-- add support for ssh/scp -->
						<!--						<dependency>-->
						<!--							<groupId>org.apache.maven.wagon</groupId>-->
						<!--							<artifactId>wagon</artifactId>-->
						<!--							<version>3.5.3</version>-->
						<!--						</dependency>-->
					</dependencies>
				</plugin>
				<plugin>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.19</version>
					<dependencies>
						<dependency>
							<groupId>org.apache.maven.surefire</groupId>
							<artifactId>surefire-testng</artifactId>
							<version>2.19.1</version>
						</dependency>
						<dependency>
							<groupId>org.apache.maven.surefire</groupId>
							<artifactId>surefire-junit47</artifactId>
							<version>2.19.1</version>
						</dependency>
					</dependencies>
					<configuration>
						<threadCount>1</threadCount>
						<suiteXmlFiles>
							<suiteXmlFile>src/test/resources/testng/testng.xml</suiteXmlFile>
						</suiteXmlFiles>
						<properties>
							<property>
								<name>surefire.testng.verbose</name>
								<value>2</value>
							</property>
						</properties>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-project-info-reports-plugin</artifactId>
				<version>3.9.0</version>
				<reportSets>
					<reportSet>
						<reports>
							<report>summary</report>
							<report>licenses</report>
							<report>team</report>
							<report>scm</report>
							<report>issue-management</report>
							<report>dependencies</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>3.11.2</version>
				<configuration>
					<quiet>true</quiet>
					<links>
						<link>https://docs.oracle.com/javase/8/docs/api/</link>
					</links>
				</configuration>
				<reportSets>
					<reportSet>
						<reports>
							<report>javadoc</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jxr-plugin</artifactId>
				<version>2.3</version>
				<reportSets>
					<reportSet>
						<reports>
							<report>jxr</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-pmd-plugin</artifactId>
				<version>3.6</version>
				<configuration>
					<targetJdk>${maven.compiler.target}</targetJdk>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-report-plugin</artifactId>
				<version>2.19.1</version>
				<reportSets>
					<reportSet>
						<reports>
							<report>report</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
			<!--<plugin>-->
			<!--<groupId>org.codehaus.mojo</groupId>-->
			<!--<artifactId>cobertura-maven-plugin</artifactId>-->
			<!--<version>2.7</version>-->
			<!--</plugin>-->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>taglist-maven-plugin</artifactId>
				<version>3.2.1</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-changes-plugin</artifactId>
				<version>3.0.0-M3</version>
				<configuration>
					<addActionDate>true</addActionDate>
				</configuration>
				<reportSets>
					<reportSet>
						<reports>
							<report>changes</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
		</plugins>
	</reporting>

	<profiles>
		<profile>
			<!-- Actions to take when releasing -->
			<id>profile.release</id>
			<activation>
				<property>
					<name>performRelease</name>
					<value>true</value>
				</property>
			</activation>
			<build>
				<plugins>
					<!-- Sign artifacts -->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
						<version>1.4</version>
						<executions>
							<execution>
								<id>sign</id>
								<goals>
									<goal>sign</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
